### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kkeeyy111** [AlphaX-Projects/alphaxcore#15]
[2021-08-12 21:30:00.7017] [E] [raptoreum] System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libzmq' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibzmq: cannot open shared object file: No such file or directory
   at ZeroMQ.lib.zmq.version(Int32& major, Int32& minor, Int32& patch)
   at ZeroMQ.lib.zmq..cctor()
   --- End of inner exception stack trace ---
   at ZeroMQ.lib.zmq.ctx_new()
   at ZeroMQ.ZContext..ctor()
   at ZeroMQ.ZContext.get_Current()
   at Alphaxcore.DaemonInterface.DaemonClient.<>c__DisplayClass28_1.<ZmqSubscribeEndpoint>b__2() in /home/poolzy/alphaxcore/src/Alphaxcore/DaemonInterface/DaemonClient.cs:line 609 System.TypeInitializationException: The type initializer for 'ZeroMQ.lib.zmq' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libzmq' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibzmq: cannot open shared object file: No such file or directory
   at ZeroMQ.lib.zmq.version(Int32& major, Int32& minor, Int32& patch)
   at ZeroMQ.lib.zmq..cctor()

**Comment by seperatis** [comment]
`sudo apt-get install libzmq5`

**Comment by kkeeyy111** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlphaX-Projects/alphaxcore"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 中午1:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlphaX-Projects/alphaxcore] error (#15)





 
sudo apt-get install libzmq5
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.




Thank you for your wrong reply. The reason is "zmqblocknotifysocket" and I test that the project can't bear large ore pool. I test 1000 + miners and it will crash.

**Comment by AlphaX-Projects** [comment]
ZeroMQ not run under this version of AlphaX core
