### ISSUE TITLE
Miner starts, but gets error about update the stats

### ISSUE THREAD

**Issue by pumba0905** [AlphaX-Projects/alphaxcore#22]
My miner starts, but the stats update not works, i get the following error:

`[2021-11-27 13:02:36.8356] [E] [StatsRecorder] Npgsql.PostgresException (0x80004005): 42703: column "connectedworkers" of relation "poolstats" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at Alphaxcore.Persistence.Postgres.Repositories.StatsRepository.InsertPoolStatsAsync(IDbConnection con, IDbTransaction tx, PoolStats stats) in /alphaxcore/alphaxcore/src/Alphaxcore/Persistence/Postgres/Repositories/StatsRepository.cs:line 63
   at Alphaxcore.Mining.StatsRecorder.<>c__DisplayClass22_2.<<UpdatePoolHashratesAsync>b__3>d.MoveNext() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at Alphaxcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /alphaxcore/alphaxcore/src/Alphaxcore/Extensions/ConnectionFactoryExtensions.cs:line 74
   at Alphaxcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 236
   at Alphaxcore.Mining.StatsRecorder.<Start>b__20_0() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 119 Npgsql.PostgresException (0x80004005): 42703: column "connectedworkers" of relation "poolstats" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at Alphaxcore.Persistence.Postgres.Repositories.StatsRepository.InsertPoolStatsAsync(IDbConnection con, IDbTransaction tx, PoolStats stats) in /alphaxcore/alphaxcore/src/Alphaxcore/Persistence/Postgres/Repositories/StatsRepository.cs:line 63
   at Alphaxcore.Mining.StatsRecorder.<>c__DisplayClass22_2.<<UpdatePoolHashratesAsync>b__3>d.MoveNext() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at Alphaxcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /alphaxcore/alphaxcore/src/Alphaxcore/Extensions/ConnectionFactoryExtensions.cs:line 74
   at Alphaxcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 236
   at Alphaxcore.Mining.StatsRecorder.<Start>b__20_0() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 119    at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Dapper.SqlMapper.ExecuteImplAsync(IDbConnection cnn, CommandDefinition command, Object param) in C:\projects\dapper\Dapper\SqlMapper.Async.cs:line 678
   at Alphaxcore.Persistence.Postgres.Repositories.StatsRepository.InsertPoolStatsAsync(IDbConnection con, IDbTransaction tx, PoolStats stats) in /alphaxcore/alphaxcore/src/Alphaxcore/Persistence/Postgres/Repositories/StatsRepository.cs:line 63
   at Alphaxcore.Mining.StatsRecorder.<>c__DisplayClass22_2.<<UpdatePoolHashratesAsync>b__3>d.MoveNext() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at Alphaxcore.Extensions.ConnectionFactoryExtensions.RunTx(IConnectionFactory factory, Func`3 action, Boolean autoCommit, IsolationLevel isolation) in /alphaxcore/alphaxcore/src/Alphaxcore/Extensions/ConnectionFactoryExtensions.cs:line 74
   at Alphaxcore.Mining.StatsRecorder.UpdatePoolHashratesAsync() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 236
   at Alphaxcore.Mining.StatsRecorder.<Start>b__20_0() in /alphaxcore/alphaxcore/src/Alphaxcore/Mining/StatsRecorder.cs:line 119
`

**Comment by pumba0905** [comment]
Sorry for opening this problem on the spur of the moment :D I checked the database calmly and strangely enough the connectedworkers column was missing
